export const books = [
  {
    id: 1,
    title: "The Great Gatsby",
    author: "F. Scott Fitzgerald",
    price: 19.99,
    rating: 4.5,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fiction", "Classics"],
  },
  {
    id: 2,
    title: "To Kill a Mockingbird",
    author: "Harper Lee",
    price: 15.99,
    rating: 4.8,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fiction", "Classics"],
  },
  {
    id: 3,
    title: "Dune",
    author: "Frank Herbert",
    price: 21.99,
    rating: 4.9,
    image: "https://via.placeholder.com/200x300",
    genre: ["Science Fiction", "Fantasy"],
  },
  {
    id: 4,
    title: "The Hobbit",
    author: "J.R.R. Tolkien",
    price: 16.99,
    rating: 4.7,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fantasy", "Classics"],
  },
  {
    id: 5,
    title: "Pride and Prejudice",
    author: "Jane Austen",
    price: 12.99,
    rating: 4.6,
    image: "https://via.placeholder.com/200x300",
    genre: ["Romance", "Classics"],
  },
  {
    id: 6,
    title: "The Silent Patient",
    author: "Alex Michaelides",
    price: 24.99,
    rating: 4.3,
    image: "https://via.placeholder.com/200x300",
    genre: ["Thriller", "Mystery"],
  },
  {
    id: 7,
    title: "Atomic Habits",
    author: "James Clear",
    price: 18.99,
    rating: 4.8,
    image: "https://via.placeholder.com/200x300",
    genre: ["Self-Help", "Non-Fiction"],
  },
  {
    id: 8,
    title: "The Da Vinci Code",
    author: "Dan Brown",
    price: 14.99,
    rating: 4.2,
    image: "https://via.placeholder.com/200x300",
    genre: ["Mystery", "Thriller"],
  },
  {
    id: 9,
    title: "Sapiens",
    author: "Yuval Noah Harari",
    price: 22.99,
    rating: 4.7,
    image: "https://via.placeholder.com/200x300",
    genre: ["History", "Non-Fiction"],
  },
  {
    id: 10,
    title: "The Alchemist",
    author: "Paulo Coelho",
    price: 13.99,
    rating: 4.4,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fiction", "Philosophy"],
  },
  {
    id: 11,
    title: "1984",
    author: "George Orwell",
    price: 15.99,
    rating: 4.6,
    image: "https://via.placeholder.com/200x300",
    genre: ["Science Fiction", "Classics"],
  },
  {
    id: 12,
    title: "Think and Grow Rich",
    author: "Napoleon Hill",
    price: 17.99,
    rating: 4.5,
    image: "https://via.placeholder.com/200x300",
    genre: ["Self-Help", "Business"],
  },
  {
    id: 13,
    title: "The Midnight Library",
    author: "Matt Haig",
    price: 16.99,
    rating: 4.6,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fiction", "Fantasy"],
  },
  {
    id: 14,
    title: "Project Hail Mary",
    author: "Andy Weir",
    price: 23.99,
    rating: 4.8,
    image: "https://via.placeholder.com/200x300",
    genre: ["Science Fiction", "Adventure"],
  },
  {
    id: 15,
    title: "The Psychology of Money",
    author: "Morgan Housel",
    price: 19.99,
    rating: 4.7,
    image: "https://via.placeholder.com/200x300",
    genre: ["Finance", "Self-Help"],
  },
  {
    id: 16,
    title: "The Thursday Murder Club",
    author: "Richard Osman",
    price: 15.99,
    rating: 4.3,
    image: "https://via.placeholder.com/200x300",
    genre: ["Mystery", "Crime"],
  },
  {
    id: 17,
    title: "Where the Crawdads Sing",
    author: "Delia Owens",
    price: 17.99,
    rating: 4.8,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fiction", "Literary"],
  },
  {
    id: 18,
    title: "The Seven Husbands of Evelyn Hugo",
    author: "Taylor Jenkins Reid",
    price: 16.99,
    rating: 4.7,
    image: "https://via.placeholder.com/200x300",
    genre: ["Historical Fiction", "Romance"],
  },
  {
    id: 19,
    title: "Educated",
    author: "Tara Westover",
    price: 18.99,
    rating: 4.7,
    image: "https://via.placeholder.com/200x300",
    genre: ["Biography", "Non-Fiction"],
  },
  {
    id: 20,
    title: "The Invisible Life of Addie LaRue",
    author: "V.E. Schwab",
    price: 20.99,
    rating: 4.4,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fantasy", "Historical Fiction"],
  },
  {
    id: 21,
    title: "Rich Dad Poor Dad",
    author: "Robert T. Kiyosaki",
    price: 14.99,
    rating: 4.5,
    image: "https://via.placeholder.com/200x300",
    genre: ["Finance", "Self-Help"],
  },
  {
    id: 22,
    title: "The Song of Achilles",
    author: "Madeline Miller",
    price: 16.99,
    rating: 4.6,
    image: "https://via.placeholder.com/200x300",
    genre: ["Historical Fiction", "Romance"],
  },
  {
    id: 23,
    title: "Verity",
    author: "Colleen Hoover",
    price: 15.99,
    rating: 4.4,
    image: "https://via.placeholder.com/200x300",
    genre: ["Thriller", "Romance"],
  },
  {
    id: 24,
    title: "The House in the Cerulean Sea",
    author: "TJ Klune",
    price: 17.99,
    rating: 4.8,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fantasy", "Romance"],
  },
  {
    id: 25,
    title: "The 48 Laws of Power",
    author: "Robert Greene",
    price: 21.99,
    rating: 4.6,
    image: "https://via.placeholder.com/200x300",
    genre: ["Self-Help", "Non-Fiction"],
  },
  {
    id: 26,
    title: "It Ends with Us",
    author: "Colleen Hoover",
    price: 15.99,
    rating: 4.5,
    image: "https://via.placeholder.com/200x300",
    genre: ["Romance", "Contemporary"],
  },
  {
    id: 27,
    title: "The Subtle Art of Not Giving a F*ck",
    author: "Mark Manson",
    price: 18.99,
    rating: 4.4,
    image: "https://via.placeholder.com/200x300",
    genre: ["Self-Help", "Non-Fiction"],
  },
  {
    id: 28,
    title: "Foundation",
    author: "Isaac Asimov",
    price: 19.99,
    rating: 4.7,
    image: "https://via.placeholder.com/200x300",
    genre: ["Science Fiction", "Classics"],
  },
  {
    id: 29,
    title: "The Power of Habit",
    author: "Charles Duhigg",
    price: 16.99,
    rating: 4.6,
    image: "https://via.placeholder.com/200x300",
    genre: ["Psychology", "Self-Help"],
  },
  {
    id: 30,
    title: "Mexican Gothic",
    author: "Silvia Moreno-Garcia",
    price: 17.99,
    rating: 4.3,
    image: "https://via.placeholder.com/200x300",
    genre: ["Horror", "Historical Fiction"],
  },
  {
    id: 31,
    title: "The Lean Startup",
    author: "Eric Ries",
    price: 22.99,
    rating: 4.7,
    image: "https://via.placeholder.com/200x300",
    genre: ["Business", "Non-Fiction"],
  },
  {
    id: 32,
    title: "The Night Circus",
    author: "Erin Morgenstern",
    price: 18.99,
    rating: 4.5,
    image: "https://via.placeholder.com/200x300",
    genre: ["Fantasy", "Romance"],
  },
];
